<div class="currency_conversions">
    <div>
        USD
        <div>$0.80</div>
    </div>
    <div>
        BTC
        <div>$4,001.81</div>
    </div>
    <div>
        ETH
        <div>$137.48</div>
    </div>
    <div>
        OCT
        <div>$0.80</div>
    </div>
    <div>
        EUR
        <div>$0.60</div>
    </div>
</div>